/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.FuncionarioController;
import Model.Funcionario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dcxz
 */
public class TelaListaFuncionario extends javax.swing.JFrame {
int idUs;
boolean admin=false;
FuncionarioController controller;
    /**
     * Creates new form TelaListaFuncionario
     */
    public TelaListaFuncionario(int id) {
        initComponents();
        idUs=id;
        controller= new FuncionarioController();
        ArrayList listaF = controller.buscarTodos();
        mostrarFuncionario(listaF);
        Funcionario f=controller.buscaID(idUs);
        if(f.getNome().equals("admin") && f.getSenha().equals("admin")){
            admin=true;
            ArrayList listaFuncionarios = controller.buscarTodos();
        mostrarFuncionarioTudo(listaF);
        }
    }
private void mostrarFuncionario(ArrayList<Funcionario> listaFuncionario) {
        String col[] = {"Código", "Nome","CPF"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        for (Funcionario c : listaFuncionario) {
            Object[] data = {
                c.getId(), 
                c.getNome(),
            c.getCpf()
            };
            tableModel.addRow(data);
        }        
        Tabela = new JTable(tableModel);
        Painel.setViewportView(Tabela);
    }
private void mostrarFuncionarioTudo(ArrayList<Funcionario> listaFuncionario) {
        String col[] = {"Código", "Nome","CPF","Senha"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        for (Funcionario f : listaFuncionario) {
            Object[] data = {
                f.getId(), 
                f.getNome(),
            f.getCpf(),
            f.getSenha()
            };
            tableModel.addRow(data);
        }        
        Tabela = new JTable(tableModel);
        Painel.setViewportView(Tabela);
    }
private void mostrarErro(String x) {
        String col[] = {x};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0); 
        Tabela = new JTable(tableModel);
        Painel.setViewportView(Tabela);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        txtID = new javax.swing.JLabel();
        campoID = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        txtNome = new javax.swing.JLabel();
        btBuscar = new javax.swing.JButton();
        btManterF = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        txtTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Painel.setViewportView(Tabela);

        txtID.setText("ID:");

        txtNome.setText("Nome:");

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btManterF.setText("Manter Funcionario");
        btManterF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btManterFActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        txtTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtTitulo.setText("Funcionario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btManterF, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(txtNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btBuscar))
                            .addComponent(Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(txtTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(txtTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID)
                    .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Painel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btManterF)
                    .addComponent(btVoltar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
         ArrayList listaF = null;
        if(campoID.getText().length()>0){
           listaF = controller.buscaTodosID(Integer.parseInt(campoID.getText()));
        mostrarFuncionario(listaF);
        }else if (campoNome.getText().length()>0){
            listaF = controller.buscarNome(campoNome.getText());
        mostrarFuncionario(listaF);  
        }else listaF = controller.buscarTodos();
        mostrarFuncionario(listaF);
        if(listaF.size()<=0){
            mostrarErro("Dado não encotrado");
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        mostrarMenu(idUs);
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btManterFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btManterFActionPerformed
       if(admin)mostrarManterFuncionario(idUs);
       else aviso();
    }//GEN-LAST:event_btManterFActionPerformed
public void aviso() {
                int i = JOptionPane.showConfirmDialog(null, "Para acessar, precisa ser administrador!",
                                                      "Aviso", JOptionPane.CLOSED_OPTION);
                     repaint();
                }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListaFuncionario(5).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Painel;
    private javax.swing.JTable Tabela;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btManterF;
    private javax.swing.JButton btVoltar;
    private javax.swing.JTextField campoID;
    private javax.swing.JTextField campoNome;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
public void mostrarMenu(int id){
        TelaMenu tl = new TelaMenu(id);
        tl.setResizable(false);
        tl.setTitle("Menu");
        tl.setLocationRelativeTo(null);
        tl.setVisible(true);
        this.setVisible(false);
    }
public void mostrarManterFuncionario(int id){
        TelaManterFuncionario tl = new TelaManterFuncionario(id);
        tl.setResizable(false);
        tl.setTitle("Funcionário");
        tl.setLocationRelativeTo(null);
        tl.setVisible(true);
        this.setVisible(false);
    }
}
