/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.VendaController;
import Model.Venda;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Dcxz
 */
public class TelaManterVenda extends javax.swing.JFrame {
int idUs;
VendaController controller;
    public TelaManterVenda(int id) {
        initComponents();
        campoCodFun.requestFocus();
        invisibleOrVisible(false);
         idUs=id;
         controller = new VendaController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        txtTitulo = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        campoID = new javax.swing.JTextField();
        campoIDProduto = new javax.swing.JTextField();
        txtIdProd = new javax.swing.JLabel();
        campoCodFun = new javax.swing.JTextField();
        txtCodFun = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JLabel();
        campoPreco = new javax.swing.JTextField();
        txtPreco = new javax.swing.JLabel();
        txtData = new javax.swing.JLabel();
        spQuantidade = new javax.swing.JSpinner();
        campoData = new javax.swing.JFormattedTextField();
        btVoltar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        txtMe = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtTitulo.setText("MANTER VENDAS");

        txtID.setText("ID");

        txtIdProd.setText("Código do produto");

        txtCodFun.setText("Código do funcionário");

        txtQuantidade.setText("Quantidade");

        txtPreco.setText("Preço unitário");

        txtData.setText("Data");

        spQuantidade.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        try {
            campoData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        txtMe.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(txtTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtID)
                                    .addComponent(campoIDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdProd)
                                    .addComponent(campoCodFun, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodFun)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtQuantidade)
                                        .addGap(18, 18, 18)
                                        .addComponent(spQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(campoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPreco)
                                    .addComponent(txtData)
                                    .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(txtMe, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoIDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodFun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCodFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade)
                    .addComponent(spQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPreco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMe, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btEditar)
                    .addComponent(btBuscar)
                    .addComponent(btExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVoltar)
                    .addComponent(Limpar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        mostrarMenu(idUs);
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        if(campoID.getText().length()>0){
            Venda v = controller.buscaID(Integer.parseInt(campoID.getText()));
            if(v!=null){
                preencherVenda(v);
                invisibleOrVisible(true);
            }else txtMe.setText("Venda não encontrado!");
        }else txtMe.setText("Campo vazio!");
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        if(campoCodFun.getText().length()>0 && campoData.getText().length()>0 && campoIDProduto.getText().length()>0&& campoPreco.getText().length()>0){
            Venda v = capturarVenda();
            if(v!=null){
                controller.atualizarVenda(v);
                menssagemCerta("Atualizado com sucesso");
            }else txtMe.setText("Atualizado com erro!");
        }else txtMe.setText("Campo vazio!");
    }//GEN-LAST:event_btEditarActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        aviso();
        if(campoCodFun.getText().length()>0 && campoData.getText().length()>0 && campoIDProduto.getText().length()>0&& campoPreco.getText().length()>0){
           Venda v = capturarVenda();
            if(v!=null){
                controller.Cadastrar(v);
                menssagemCerta("Cadastrado com sucesso");
            }else txtMe.setText("Cadastrado com erro!");
        }else txtMe.setText("Campo vazio!");
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        limpar();
    }//GEN-LAST:event_LimparActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        if(campoID.getText().length()>0){
            Venda v = controller.buscaID(Integer.parseInt(campoID.getText()));
            if(v!=null){
                controller.excluirVenda(Integer.parseInt(campoID.getText()));
                limpar();
                menssagemCerta("Deletado com sucesso");
            }else txtMe.setText("Venda não encontrado!");
        }else txtMe.setText("Campo vazio!");
    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaManterVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaManterVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaManterVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaManterVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaManterVenda(15).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btVoltar;
    private javax.swing.JTextField campoCodFun;
    private javax.swing.JFormattedTextField campoData;
    private javax.swing.JTextField campoID;
    private javax.swing.JTextField campoIDProduto;
    private javax.swing.JTextField campoPreco;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spQuantidade;
    private javax.swing.JLabel txtCodFun;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtIdProd;
    private javax.swing.JLabel txtMe;
    private javax.swing.JLabel txtPreco;
    private javax.swing.JLabel txtQuantidade;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
public Venda capturarVenda(){
    int id=0;
    if(campoID.getText().length()>0){
     id = Integer.parseInt(campoID.getText());
    }
    int idProduto= Integer.parseInt(campoIDProduto.getText());
        int idFuncionario= Integer.parseInt(campoCodFun.getText());
        int quantidade= Integer.parseInt(spQuantidade.getValue().toString());
        double preco= Double.parseDouble(campoPreco.getText());
        String data = campoData.getText();
        Venda v = new Venda(id, idProduto, idFuncionario, quantidade, preco, data);
        return v;
}
public void menssagemCerta(String x){
    txtMe.setText(x);
    txtMe.setForeground(Color.BLUE);
}
public void invisibleOrVisible(boolean x){
    btEditar.setVisible(x);
    btExcluir.setVisible(x);
}
private void preencherVenda(Venda v){
    campoCodFun.setText(""+v.getIdFuncionario());
    campoID.setText(""+v.getId());
    campoData.setText(""+v.getData());
    campoIDProduto.setText(""+v.getIdProduto());
    campoPreco.setText(""+v.getPreco());
    spQuantidade.setValue(v.getQuantidade());
    
}
public void limpar(){
    campoCodFun.setText("");
    campoID.setText("");
    campoData.setText("");
    campoIDProduto.setText("");
    campoPreco.setText("");
    spQuantidade.setValue(0);
    txtMe.setText("");
}
public void mostrarListaCliente(){
         TelaListaCliente tl = new TelaListaCliente(idUs);
        tl.setResizable(false);
        tl.setTitle("Lista Cliente");
        tl.setLocationRelativeTo(null);
        tl.setVisible(true);
        tl.setVisible(true);
        tl.setDefaultCloseOperation(tl.HIDE_ON_CLOSE);
        
    }
 public void aviso() {
                int i = JOptionPane.showConfirmDialog(null, "Para o cadastro, o campo de código estara indisponivel",
                                                      "Aviso", JOptionPane.CLOSED_OPTION);
                     repaint();
                }

 public void mostrarMenu(int id){
        TelaListaVenda tl = new TelaListaVenda(id);
        tl.setResizable(false);
        tl.setTitle("Venda");
        tl.setLocationRelativeTo(null);
        tl.setVisible(true);
        this.setVisible(false);
    }
}
