/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ProdutoController;
import Model.Produto;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Dcxz
 */
public class TelaManterProduto extends javax.swing.JFrame {
int idUs;
ProdutoController controller;
    /**
     * Creates new form TelaCadastroProduto
     */
    public TelaManterProduto(int id) {
        initComponents();
        campoMarca.requestFocus();
        idUs=id;
         invisibleOrVisible(false);
        controller = new ProdutoController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMarca = new javax.swing.JLabel();
        campoMarca = new javax.swing.JTextField();
        campoModelo = new javax.swing.JTextField();
        txtModelo = new javax.swing.JLabel();
        campoNumeracao = new javax.swing.JTextField();
        txtNumeracao = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JLabel();
        campoPreco = new javax.swing.JTextField();
        txtPreco = new javax.swing.JLabel();
        spFornecedor = new javax.swing.JSpinner();
        spQuantidade = new javax.swing.JSpinner();
        txtInformativo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JLabel();
        cbInformativo = new javax.swing.JComboBox<>();
        btVoltar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        txtMe = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        campoID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtMarca.setText("Marca");

        campoModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoModeloActionPerformed(evt);
            }
        });

        txtModelo.setText("Modelo");

        txtNumeracao.setText("Numeracao");

        txtFornecedor.setText("Nº Fornecedor");

        txtQuantidade.setText("Quantidade");

        txtPreco.setText("Preço");

        spFornecedor.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9, 1));
        spFornecedor.setToolTipText("");
        spFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        spQuantidade.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        txtInformativo.setForeground(new java.awt.Color(0, 153, 153));
        txtInformativo.setText("Lista de Fornecedor");

        txtTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTitulo.setText("MANTER PRODUTO");

        cbInformativo.setForeground(new java.awt.Color(0, 153, 153));
        cbInformativo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1-Nike", "2-Adidas", "3-TenisPe", "5-Sao Calçados", "6- Topper", "7-Vision", "8-Senarks", "9-TGH" }));

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        txtMe.setForeground(new java.awt.Color(255, 0, 0));

        txtID.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(txtMe, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(btCadastrar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPreco)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(txtInformativo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbInformativo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtQuantidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtFornecedor)
                            .addComponent(txtNumeracao)
                            .addComponent(campoNumeracao, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModelo)
                            .addComponent(campoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMarca)
                            .addComponent(campoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campoID, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTitulo)
                                .addComponent(campoMarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitulo)
                .addGap(2, 2, 2)
                .addComponent(txtID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtModelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeracao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNumeracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInformativo)
                    .addComponent(cbInformativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade)
                    .addComponent(spQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPreco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMe, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btEditar)
                    .addComponent(btBuscar)
                    .addComponent(btExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVoltar)
                    .addComponent(Limpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoModeloActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        mostrarEstoque();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        if(campoID.getText().length()>0){
            Produto c = controller.buscaID(Integer.parseInt(campoID.getText()));
            if(c!=null){
                preencherProduto(c);
                invisibleOrVisible(true);
            }else txtMe.setText("Produto não encontrado!");
        }else txtMe.setText("Campo vazio!");
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        if(campoMarca.getText().length()>0 && campoModelo.getText().length()>0 && campoNumeracao.getText().length()>0&& campoPreco.getText().length()>0){
            Produto p = capturarProduto();
            if(p!=null){
                controller.atualizarProduto(p);
                menssagemCerta("Atualizado com sucesso");
            }else txtMe.setText("Atualizado com erro!");
        }else txtMe.setText("Campo vazio!");
    }//GEN-LAST:event_btEditarActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        aviso();
        if(campoMarca.getText().length()>0 && campoModelo.getText().length()>0 && campoNumeracao.getText().length()>0&& campoPreco.getText().length()>0){
           Produto p = capturarProduto();
            if(p!=null){
                controller.Cadastrar(p);
                menssagemCerta("Cadastrado com sucesso");
            }else txtMe.setText("Cadastrado com erro!");
        }else txtMe.setText("Campo vazio!");
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        limpar();
    }//GEN-LAST:event_LimparActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        if(campoID.getText().length()>0){
            Produto p = controller.buscaID(Integer.parseInt(campoID.getText()));
            if(p!=null){
                controller.excluirProduto(Integer.parseInt(campoID.getText()));
                limpar();
                menssagemCerta("Deletado com sucesso");
            }else txtMe.setText("Produto não encontrado!");
        }else txtMe.setText("Campo vazio!");
    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaManterProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaManterProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaManterProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaManterProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaManterProduto(3).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btVoltar;
    private javax.swing.JTextField campoID;
    private javax.swing.JTextField campoMarca;
    private javax.swing.JTextField campoModelo;
    private javax.swing.JTextField campoNumeracao;
    private javax.swing.JTextField campoPreco;
    private javax.swing.JComboBox<String> cbInformativo;
    private javax.swing.JSpinner spFornecedor;
    private javax.swing.JSpinner spQuantidade;
    private javax.swing.JLabel txtFornecedor;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtInformativo;
    private javax.swing.JLabel txtMarca;
    private javax.swing.JLabel txtMe;
    private javax.swing.JLabel txtModelo;
    private javax.swing.JLabel txtNumeracao;
    private javax.swing.JLabel txtPreco;
    private javax.swing.JLabel txtQuantidade;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
public Produto capturarProduto(){
    int id=0;
    if(campoID.getText().length()>0){
     id = Integer.parseInt(campoID.getText());
    }
        String marca =campoMarca.getText();
        String modelo = campoModelo.getText();
        int numeracao = Integer.parseInt(campoNumeracao.getText());
        int id_fornecedor =  Integer.parseInt(spFornecedor.getValue().toString());
        int quantidade =  Integer.parseInt(spQuantidade.getValue().toString());
        double preco = Double.parseDouble(campoPreco.getText());
        Produto p = new Produto(id, marca, modelo, numeracao, id_fornecedor, quantidade, preco);
        return p;
}
public void menssagemCerta(String x){
    txtMe.setText(x);
    txtMe.setForeground(Color.BLUE);
}
public void invisibleOrVisible(boolean x){
    btEditar.setVisible(x);
    btExcluir.setVisible(x);
}
private void preencherProduto(Produto p){
    campoMarca.setText(p.getMarca());
    campoID.setText(""+p.getId());
    campoModelo.setText(""+p.getModelo());
    campoNumeracao.setText(""+p.getNumeracao());
    campoPreco.setText(""+p.getPreco());
    spFornecedor.setValue(p.getIdFornecedor());
    spQuantidade.setValue(p.getQuantidade());
}
public void limpar(){
    campoMarca.setText("");
    campoID.setText("");
    campoModelo.setText("");
    campoNumeracao.setText("");
    campoPreco.setText("");
    spFornecedor.setValue(1);
    spQuantidade.setValue(1);
}
public void mostrarEstoque(){
         TelaEstoque tl = new TelaEstoque(idUs);
        tl.setResizable(false);
        tl.setTitle("Estoque de Produto");
        tl.setLocationRelativeTo(null);
        tl.setVisible(true);
        tl.setVisible(true);
        
    }
 public void aviso() {
                int i = JOptionPane.showConfirmDialog(null, "Para o cadastro, o campo de código estara indisponivel",
                                                      "Aviso", JOptionPane.CLOSED_OPTION);
                     repaint();
                }

}
